name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build zipped release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifact: "release.zip"
        body: "Update"
        token: ${{ secrets.GITHUB_TOKEN }}
